### ISSUE TITLE
Container action is only supported on linux

### ISSUE THREAD

**Issue by sayyid5416** [JackMcKew/pyinstaller-action-windows#12]
```
name: Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
```
![image](https://user-images.githubusercontent.com/78584556/110669782-b09bc780-81f2-11eb-8cde-99dd7d3f6399.png)

Check action here: https://github.com/hussain5416/pyinstaller-example/actions

**Comment by JackMcKew** [comment]
I take it this was solved?

**Comment by sayyid5416** [comment]
@JackMcKew I don't understand, what the problem was, but after changing my `.yml` file. Problem got solved. New yml:
```
name: Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: Links extractor
        path: src/dist/windows # or path/to/artifact
```
