### ISSUE TITLE
Confused about how to setup multiple .spec file

### ISSUE THREAD

**Issue by Sedatyf** [JackMcKew/pyinstaller-action-windows#13]
Hi,

First of all, thank you to bring pyInstaller in GitHub Actions. It's a great idea!
I read the documentation and there is a part where it says 
> The source code directory should have your .spec file that PyInstaller generates. If you don't have one, you'll need to run PyInstaller once locally to generate it. Also if you have another program .spec file you can set specific pyinstaller .spec file by spec: <YOUR_SPEC_FILE_NAME>

But I'm not too sure how to setup it. Here is my yaml file
```yaml
name: Package Application with Pyinstaller for Windows

on:
  push:
    branches: [ gui ]
  pull_request:
    branches: [ gui ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: src/main_windows.spec

    - uses: actions/upload-artifact@v2
      with:
        name: PCC-Win
        path: src/dist/main
```
And my project folder tree is like this
```
project/
    src/
        img/
        package/
        main_windows.spec
```
But when GitHub Actions tries to build this project, it returns me a ``spec "src/main_windows.spec" not found``
Am I missing something?

Thanks in advance,
Sedatyf
