### ISSUE TITLE
Binary not outputed to bin/ ?

### ISSUE THREAD

**Issue by jdev082** [JackMcKew/pyinstaller-action-windows#24]
Here's the YML file of the action

```
name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: aurapad.exe
        path: bin
```
It doesn't fail, but still doesn't put the file in bin dir
