### ISSUE TITLE
OSError: [WinError 123] Invalid name: '/tmp\\*'

### ISSUE THREAD

**Issue by kleag** [JackMcKew/pyinstaller-action-windows#28]
Hi,

As in #3 , I get the error from the title. The proposed solution does not work: I have a spec file.

Here is the repo: https://github.com/kleag/annotate_translation
The failed action: https://github.com/kleag/annotate_translation/actions/runs/3195325548/jobs/5215851413

And my action file: https://github.com/kleag/annotate_translation/blob/main/.github/workflows/pyinstaller-windows.yml
```
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: annotation-exe
        path: src/dist/windows
```
