### ISSUE TITLE
Support git pip packages

### ISSUE THREAD

**Issue by LucaAngioloni** [JackMcKew/pyinstaller-action-windows#35]
At the moment, during the `requirements.txt` installation we cannot install packages from `git` for example with this line in `requirements.txt`:

```
package-name @ git+https://github.com/name/repo.git
```

This is because git is not installed in wine and we get this errors:

> ERROR: Error [WinError 2] File not found while executing command git version
> ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

I believe it would be enough to install git in wine. I am not sure though were this can be done and how to keep all the various platforms in mind. Maybe not in this repo but in [cdrx/docker-pyinstaller](https://github.com/cdrx/docker-pyinstaller)?

**Comment by JackMcKew** [comment]
Can you please test your workflow against the new branch `python3-10-pyinstaller-5-3` and let me know your results

Example:

```
- name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src
```
