### ISSUE TITLE
setting path to root not working

### ISSUE THREAD

**Issue by TomW1605** [JackMcKew/pyinstaller-action-windows#38]
i tried `path: .` as recomended in #8 and also `path: /` and `path: ` but i keep getting `OSError: [WinError 123] Invalid name: '/tmp\\*'`

**Comment by JackMcKew** [comment]
Hi Tom,

Would you mind providing a reproducible example please

**Comment by TomW1605** [comment]
https://github.com/TomW1605/Fusion360_Slicer_Selector_test

**Comment by JackMcKew** [comment]
Please make sure to include a `.spec` file which instructs Pyinstaller how to package your application

If you provide a `.spec` file in the path that you set (ie, `.`) then the action can run as expected

Let me know if any dramas, check the `README` for more information about this

**Comment by TomW1605** [comment]
thanks i dont know how i missed that. i try it on the weekend when i have time

**Comment by EnzoDeg40** [comment]
When I set path to `.` i have error `OSError: [WinError 123] Invalid name: 'Z:\\tmp\\*'` (name: Package Application)
Note : I do have a file called space.spec in my project
```yml
  - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: space
        path: src/dist/windows
```
