### ISSUE TITLE
Erroring on Package

### ISSUE THREAD

**Issue by HahnJustin** [JackMcKew/pyinstaller-action-windows#46]
Hi, I've been getting an error when I try to run this github action.
Here is the output specifically of the 'Package Application'

```
Run JackMcKew/pyinstaller-action-windows@main
/usr/bin/docker run --name e769b195c2a96442ba182150481d60f92_196973 --label 31500e --workdir /github/workspace --rm -e "INPUT_PATH" -e "INPUT_SPEC" -e "INPUT_REQUIREMENTS" -e "INPUT_PYPI_URL" -e "INPUT_PYPI_INDEX_URL" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Internet-Manager/Internet-Manager":"/github/workspace" 31500e:769b195c2a96442ba182150481d60f92  "src" "https://pypi.python.org/" "https://pypi.python.org/simple" "internet_manager.spec" "requirements/requirements-gui.txt"
0044:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0044:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
0044:err:systray:initialize_systray Could not create tray window
Requirement already satisfied: pip in c:\python310\lib\site-packages (24.0)
Collecting wheel
  Downloading wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: setuptools in c:\python310\lib\site-packages (58.1.0)
Collecting setuptools
  Downloading setuptools-69.2.0-py3-none-any.whl.metadata (6.3 kB)
Downloading wheel-0.43.0-py3-none-any.whl (65 kB)
   ---------------------------------------- 65.8/65.8 kB 4.3 MB/s eta 0:00:00
Downloading setuptools-69.2.0-py3-none-any.whl (821 kB)
   --------------------------------------- 821.5/821.5 kB 33.8 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
Successfully installed setuptools-69.2.0 wheel-0.43.0
/entrypoint.sh: line 42: cd: src: No such file or directory
```

My main.yaml is:
```yaml
name: Package with PyInstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-internet-manager:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: internet_manager.spec
        requirements: "requirements/requirements-gui.txt"

    - uses: actions/upload-artifact@v2
      with:
        name: internet_manager
        path: src/dist

  build-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: server.spec
        requirements: "requirements/requirements-server.txt"

    - uses: actions/upload-artifact@v2
      with:
        name: server
        path: src/dist
```

Also, both jobs failed in the same way above. I can also add the spec files if need be, but I don't really understand why I'm having this issue. Also, side note, it might be good to remove the part about Python 3.10 from the read-me, since I don't think that branch exists anymore.

Thanks!
